Scenario
Remember this module’s scenario in which you’re working for a software development company in the retail industry that is planning to migrate its online store to a new app but is experiencing difficulties planning the project due to little collaboration and communication between the development and operations teams. Since you have decided to use GitHub for Agile planning and management, this lab gives you the opportunity to create a GitHub repo, associated milestones and issues, a project, and project board. Additionally, you’ll be able to add a draft item to the project board and an item based on an issue and review the automation settings.

Objectives
In this lab, you will:

Create a GitHub repo, project, and project board
Create and manage project board items

Task 1: Create a GitHub project
On the GitHub main page, select the avatar icon at the right side of the toolbar and, in the drop-down menu, select Your projects.
Select New project.
In the Select a template pane, select Team planning, and then select Create project.

Note: Alternatively, you could start from scratch and display the project in the table, board, or roadmap format.

On the new project page, select the autogenerated project name. This will automatically display the Project settings page.
In the Project name text box, enter DevOps Core Intro Project.
In the Short description text box, enter Introduction to GitHub Projects and select Save.

In the README section, enter the following text

Note: The README section includes a simplified Markdown editor, assisting you with creating visually appealing README page for the project. You could use the toolbar icons to format the text and use the Preview tab to review the resulting changes. Copy and paste the following text into the README editor section:

code
### Welcome to DevOps Core Intro Project ###

**Projects are a customizable, flexible tool for planning and tracking your work.**

To find out more, refer to GitHub documentation [about Projects](https://docs.github.com/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
Select Preview to review the resulting page.
Select Save.
Scroll down to the Danger zone and note the option allowing you to switch the visibility of the project between Private and Public, close the project, and delete it.

Note: Do not close or delete the project at this point. Only note the options available to you.

Scroll up to the top of the page and note that you have the options to Manage access to the project and create custom fields in the project interface.
Select the left facing arrow in the <- Settings label to exit the Settings page.

Task 2: Create a GitHub project board
On the DevOps Core Intro Project page, select the down-facing caret next to the Backlog tab and, in the Layout section, select Board.

Note: You can use this option to easily switch between the table, board, and roadmap views.

Review the resulting page that consists of three predefined columns labeled:

Todo - including items which haven’t been started
In Progress - including items being actively worked on
Done - including items that have been completed
Note: This layout represents a very basic Kanban board. Within each column, you can add individual items. You can also add extra columns.

To add an extra column, select the + icon to the right of the Done column and then select + New Column.
In the New option window, in the Label text text box, enter Review In Progress and select a color you want to assign to the column. In the Description text box, enter This item is being reviewed, and then select Save.
Select the small circle next to the Review in Progress label of the newly added column and use it to drag it between the In Progress and Done column.

Lab- Implement Flow of Work with GitHub
Scenario
Remember this module’s scenario in which you’re working for a software development company in the retail industry that is planning to migrate an online store from an old app to a new app called eShopOnWeb. Since you have decided to use Git and GitHub to facilitate application lifecycle management, this lab gives you the opportunity to start by forking an existing repo, configuring it, creating an issue, creating a branch, updating files in the branch, creating and merging a pull request, closing the issue and validating the changes.

Objectives
In this lab, you will:

Implement and manage repos with GitHub

Prerequisites
In this exercise, you’ll fork a Git repo and manage it by using GitHub.

Task 1: Fork a GitHub repo
Task 2: Configure a GitHub repo
Task 3: Create an issue
Task 4: Create a branch
Task 5: Update files in the branch
Task 6: Create and merge a pull request
Task 7: Close the issue
Task 8: Validate the changes
Task 1: Fork a GitHub repo
Start a web browser and navigate to the GitHub home page.
When prompted to authenticate, sign in by using your GitHub user account.
Open another tab in the same browser window and navigate to the Spoon-Knife repo.
On the Spoon-Knife repo page, select Fork.
On the Create a new fork page, ensure that the Owner drop-down list entry displays your GitHub user name, accept the default entry Spoon-Knife in the Repository name text box, leave the Copy the main branch only checkbox enabled, and then select Create fork.

Note: Your browser session will be automatically redirected to the newly forked repo.

Task 2: Configure a GitHub repo
On the forked Spoon-Knife repo page, in the toolbar, select Settings.
In the General section of the Settings tab, note that the default branch is set to *main.
Navigate to the Features area of the General section and enable the Issues checkbox.
In the left side navigational menu, in the Code and automation grouping, select the Pages entry.
In the GitHub Pages pane, in the Branch section, change the None entry in the drop-down list to main and then select Save.

Note: GitHub Pages will automatically publish the content of the repo to a site accessible via the URL https://<your_GitHub_username>.github.io/Spoon-Knife/.

In the GitHub Pages pane, select the Visit site button. This will automatically open another web browser tab and display the page representing the current content of the index.html file.

Note: You might need to wait a few minutes before the Visit site button and the page become available.

Note: Perform the remaining steps of this task if you completed the first lab.

Back on the forked Spoon-Knife repo page, in the toolbar, select Projects.
On the Welcome to the all-new projects pane, select Link a project, and, in the drop-down menu, select Link an existing project.
In the list of the existing projects, select DevOps Core Intro Project.
Task 3: Create an issue
On the forked Spoon-Knife page, select the Issues tab.
On the Welcome to issues! page, select New issue.
In the Add a title text box, enter index.html looks rather austere.
In the Add a description text box, enter index.html file can use a modern touch.
In the current pane, in the Assignees section, select Add assignees…, and, in the Suggestions section, select your GitHub user name.
Select the gear icon next to the Labels entry and, in the drop-down list, select enhancement.
Select the gear icon next to the Projects entry and, in the drop-down list, select DevOps Core Intro Project.
Click Create to save the new issue.
Open the new issue again.
On the index.html looks rather austere pane, in the Projects section, set Status to In Progress.
On the forked Spoon-Knife page, select the Projects tab.
On the Welcome to the all-new projects page, select DevOps Core Intro Project.
In the board view of the DevOps Core Intro Project, review the In Progress column and note that it includes the newly created issue.
Task 4: Create a branch
Switch back to the Code tab.
In the upper left corner of the page, select the main entry to display the Switch branches/tags drop-down list.
In the Find or create a branch… text box, enter update index.html and then select Create branch: update index.html from ‘main’ entry to create a new branch.

Note: This will automatically make the newly created branch the current one, as indicated by the content of the drop-down list.

Task 5: Update files in the branch
On the forked Spoon-Knife repo page, in the listing of files, select index.html.
On the Spoon-Knife/index.html page, on the right side in the code editor toolbar, select the pencil icon to switch to the editor mode.
In the editor pane, replace the entire body element of the page (lines 12-17) with the following HTML code:

code
<div id="octocat">
  <img src="https://octodex.github.com/images/NUX_Octodex.gif" alt="Octocat Image">
</div>

<p>
  Ready to team up? Let's collaborate, @octocat!
</p>
In the upper right corner of the editor page, select Commit changes….
In the Commit changes window, in the Extended description text box, enter Modified the image and paragraph text, accept the default commit message, and select Commit changes.

Note: You also have the option to create a new branch for the commit at this point.

In the listing of repo files on the left side, select styles.css.
On the Spoon-Knife/styles.css page, on the right side in the code editor toolbar, select the pencil icon to switch to the editor mode.
In the editor pane, replace the line 17 with the entire following HTML code:

code
  color: #333;
  line-height: 1.5;
  text-align: center;
}

body {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  background-color: #f8f9fa;
}

#octocat img {
  display: block;
  width: 100%;
  height: auto;
}

In the upper right corner of the editor page, select Commit changes….
In the Commit changes window, in the Extended description text box, enter Modified CSS tags and selectors, accept the default commit message, and select Commit changes to commit changes to the update-index.html branch.
Task 6: Create and merge a pull request
Navigate back to the forked Spoon-Knife repo page.
Ensure that you’re currently viewing the update-index.html branch, as indicated by the label appearing in the drop-down list in the upper-left corner of the page. If that label displays main, select it first and then, in the drop-down list containing the list of branches, select update-index.html.
On the forked Spoon-Knife repo page, select Contribute and then select Open pull request.
On the Open a pull request page, select the entry base repository: octocat/Spoon-Knife.
In the Choose a Base Repository drop-down list, select the name of the forked repository you created at the beginning of this lab.

Note: The name will start with your GitHub name, followed by a forward slash, followed by Spoon-Knife. Once you select it, the entry should change to base: main.

Note: This is necessary because we want to update the main branch in the forked repo, rather than the main branch in the repo from which you created the fork.

In the Add a title text box, replace Update index.html with Update index.html and styles.css.

In the Add a description text box, enter Addressing #1 and select Create pull request.

Note: By including #1, you are able to reference the first issue associated with this pull request.

Verify that the current branch has no conflicts with the base branch, select Merge pull request, and then select Confirm merge.
Verify that the pull request has been successfully merged and closed and select Delete branch.
Task 7: Close the issue
In the toolbar of the GitHub page, select the Issues tab.
Select the checkbox to the left of the first issue index.html looks rather austere, select Mark as, and in the drop-down list, select Closed.
Navigate back to the board view of the DevOps Core Intro Project and note that the issue appears now in the Done column.
Task 8: Validate the changes
In the web browser window, navigate back to your forked Spoon-Knife repo page, select the Settings tab and then, in the left side navigation menu, in the Code and automation grouping, select Pages to display the GitHub Pages pane.
In the GitHub Pages pane, select Visit site to open another browser tab displaying the updated content of the index.html file.
Verify that the page has been updated to include the visual elements referenced in the HTML and CSS files.
Note: At this point, you could potentially submit changes to the main branch in your fork back to the original repo. This would be typically the next step when developing updates and collaborating on open-source projects. However, since the original repo is not maintained, this step is not applicable here.
